repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: fadedefae2df9fa6dff624fab733d717aea5ca0e
    hooks:
    - id: flake8
